blank_issues_enabled: false
contact_links:
  - name: Ask a Question
    url: https://github.com/PyTorchLightning/pytorch-lightning/discussions/new
    about: Ask and answer Lightning related questions
  - name: 💬 Slack
    url: https://pytorch-lightning.slack.com/join/shared_invite/zt-12iz3cds1-uyyyBYJLiaL2bqVmMN7n~A
    about: Chat with our community
